version: '3.8'

services:
  product-service:
    image: astar5327/product-admin-service:latest
    container_name: product-admin-service
    ports:
      - "0:8080"  # 랜덤 포트 매핑
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MONGO_USER=root
      - MONGO_PASSWORD=1234
    networks:
      - msa-network

networks:
  msa-network:
    external: true